當 [formGroup] 放在 <form> 標籤下的時候，#tForm="ngForm" 會得到 FormGroupDirective 型別的物件
    ERROR in src/app/login2/login2.component.html:30:56 - error TS2345: Argument of type 'FormGroupDirective' is not assignable to parameter of type 'NgForm'.
      Type 'FormGroupDirective' is missing the following properties from type 'NgForm': _directives, options, ngAfterViewInit, controls, and 2 more.

    30                   #tForm="ngForm" (ngSubmit)="doSubmit(tForm)">
                                                              ~~~~~

      src/app/login2/login2.component.ts:6:16
        6   templateUrl: './login2.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component Login2Component.